version: '3'

services:
  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 启用 JMX 暴露指标
      - KAFKA_JMX_ENABLED=true
      - JMX_PORT=5555
    volumes:
      - kafka-data:/opt/kafka-logs
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    environment:
      - KAFKA_BROKERS=kafka:9092
    ports:
      - "9308:9308"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  kafka-data:

networks:
  monitoring:
    driver: bridge