management:
  server:
    port: 8084
  endpoints:
    jmx:
      exposure:
        include: *
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true